<a href="https://colab.research.google.com/github/felrojas1/MiPrimeraAplicacionS31/blob/master/Te_damos_la_bienvenida_a_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Pokemon.csv to Pokemon.csv

In [27]:
import pandas as pd

df = pd.read_csv('Pokemon.csv')
df.head()

pd.options.display.max_rows = 9999

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [16]:
df['Type 1'].unique()

df['Type 1'].value_counts() #ver frecuencia de cada categoria

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

In [7]:
for col in ['Type 1', 'Type 2', 'Generation', 'Legendary']:
    print(f"\nColumna: {col}")
    print("Cantidad de categorías:", df[col].nunique())
    print(df[col].value_counts())

Columna: Type 1
Cantidad de categorías: 18
Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

Columna: Type 2
Cantidad de categorías: 18
Type 2
Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Ice         14
Rock        14
Water       14
Ghost       14
Fire        12
Electric     6
Normal       4
Bug          3
Name: count, dtype: int64

Columna: Generation
Cantidad de categorías: 6
Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64

Columna: Legendary
Cantidad de categorías: 2
Legendary
False    735
True      65
Name: count, dtype: int64

In [8]:
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [11]:
cant_cat_subcat = df['Type 1'].value_counts()
print(cant_cat_subcat['Water'])

112

In [24]:
df.describe().round()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0,800.0
mean,363.0,435.0,69.0,79.0,74.0,73.0,72.0,68.0,3.0
std,208.0,120.0,26.0,32.0,31.0,33.0,28.0,29.0,2.0
min,1.0,180.0,1.0,5.0,5.0,10.0,20.0,5.0,1.0
25%,185.0,330.0,50.0,55.0,50.0,50.0,50.0,45.0,2.0
50%,364.0,450.0,65.0,75.0,70.0,65.0,70.0,65.0,3.0
75%,539.0,515.0,80.0,100.0,90.0,95.0,90.0,90.0,5.0
max,721.0,780.0,255.0,190.0,230.0,194.0,230.0,180.0,6.0

total